workflows:
  ios-signed-build:
    name: iOS Signed IPA Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    
    environment:
      vars:
        XCODE_PROJECT: "LemonClicker.xcodeproj"
        XCODE_SCHEME: "LemonClicker"
        BUNDLE_ID: "com.sinotruk.cnhtc.srm"
        TEAM_ID: "Y75T79946S"
      
      ios_signing:
        distribution_type: enterprise
        bundle_identifier: com.sinotruk.cnhtc.srm

    scripts:
      - name: Set up code signing
        script: |
          # Install profiles and set up keychain
          xcode-project use-profiles
        
      - name: Build and Package Signed IPA
        script: |
          # 1. Find the UUID of the installed provisioning profile
          PROVISIONING_PROFILE_UUID=$(grep UUID -A1 -a ~/Library/MobileDevice/Provisioning\ Profiles/*.mobileprovision | grep -io "[-A-Z0-9]\{36\}" | head -n 1)
          echo "Detected Provisioning Profile UUID: $PROVISIONING_PROFILE_UUID"

          # 2. Create ExportOptions.plist
          cat > ExportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>enterprise</string>
              <key>teamID</key>
              <string>$TEAM_ID</string>
              <key>compileBitcode</key>
              <false/>
              <key>signingStyle</key>
              <string>manual</string>
              <key>provisioningProfiles</key>
              <dict>
                  <key>$BUNDLE_ID</key>
                  <string>$PROVISIONING_PROFILE_UUID</string>
              </dict>
          </dict>
          </plist>
          EOF

          # 3. Build Archive using pure manual signing
          xcodebuild archive \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -archivePath build/LemonClicker.xcarchive \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            CODE_SIGN_IDENTITY="iPhone Distribution" \
            PROVISIONING_PROFILE_SPECIFIER="$PROVISIONING_PROFILE_UUID" \
            AD_HOC_CODE_SIGNING_ALLOWED=YES

          # 4. Export IPA
          xcodebuild -exportArchive \
            -archivePath build/LemonClicker.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build/ipa
            
    artifacts:
      - build/ipa/*.ipa
      - /tmp/xcodebuild_log/*.log
      
    publishing:
      email:
        recipients:
          - user@example.com
