workflows:
  ios-signed-build:
    name: iOS Signed IPA Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    
    environment:
      vars:
        XCODE_PROJECT: "LemonClicker.xcodeproj"
        XCODE_SCHEME: "LemonClicker"
        BUNDLE_ID: "com.example.lemonclicker"
      
      ios_signing:
        # This will use the files you upload to the Codemagic UI
        distribution_type: ad_hoc
        bundle_identifier: com.example.lemonclicker

    scripts:
      - name: Set up code signing
        script: |
          # This command fetches the certificates and profiles you uploaded to Codemagic
          xcode-project use-profiles
        
      - name: Build and Package Signed IPA
        script: |
          # Build for a real device and package into .ipa
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME" \
            --configuration Release \
            --export-method ad-hoc \
            --output "build/ios/LemonClicker.ipa"
            
    artifacts:
      - build/ios/*.ipa
      - /tmp/xcodebuild_log/*.log
      
    publishing:
      email:
        recipients:
          - user@example.com
