workflows:
  ios-signed-build:
    name: iOS Signed IPA Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    
    environment:
      vars:
        XCODE_PROJECT: "LemonClicker.xcodeproj"
        XCODE_SCHEME: "LemonClicker"
      
      ios_signing:
        distribution_type: enterprise
        bundle_identifier: com.sinotruk.cnhtc.srm

    scripts:
      - name: Set up code signing
        script: |
          # This will set up the keychain and install the profiles
          xcode-project use-profiles
        
      - name: Build and Package Signed IPA
        script: |
          # We use the environment variables set by 'use-profiles'
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME" \
            --bundle-id "com.sinotruk.cnhtc.srm"
            
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_log/*.log
      
    publishing:
      email:
        recipients:
          - user@example.com
