workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    
    environment:
      vars:
        XCODE_PROJECT: "LemonClicker.xcodeproj"
        XCODE_SCHEME: "LemonClicker"
        BUNDLE_ID: "com.example.lemonclicker"
      
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: com.example.lemonclicker

    scripts:
      - name: Set up code signing
        script: xcode-project use-profiles
        
      - name: Build iOS App (.app)
        script: |
          xcodebuild build \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -derivedDataPath build \
            -destination 'generic/platform=iOS'
            
      - name: Package .app into .ipa
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME" \
            --configuration Release \
            --export-method ad-hoc \
            --output "build/ios/LemonClicker.ipa"

    artifacts:
      - build/ios/*.ipa
      - /tmp/xcodebuild_log/*.log
      
    publishing:
      email:
        recipients:
          - $DEVELOPER_EMAIL
      slack:
        channel: $SLACK_CHANNEL
        notify_on_build_start: true
