workflows:
  ios-unsigned-build:
    name: iOS Unsigned Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    
    environment:
      vars:
        XCODE_PROJECT: "LemonClicker.xcodeproj"
        XCODE_SCHEME: "LemonClicker"

    scripts:
      - name: Build Unsigned iOS App
        script: |
          # Build for a real device but skip signing
          xcodebuild build \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
            
      - name: Package .app into zip
        script: |
          # Find the .app and zip it for easy download
          cd build/Build/Products/Release-iphoneos
          zip -r ../../../LemonClicker_Unsigned.zip LemonClicker.app
          
    artifacts:
      - "*.zip"
      - build/Build/Products/Release-iphoneos/*.app
      
    publishing:
      email:
        recipients:
          - user@example.com
