workflows:
  ios-signed-build:
    name: iOS Signed IPA Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    
    environment:
      vars:
        XCODE_PROJECT: "LemonClicker.xcodeproj"
        XCODE_SCHEME: "LemonClicker"
        BUNDLE_ID: "com.sinotruk.cnhtc.srm"
        TEAM_ID: "Y75T79946S"
        PROFILE_NAME: "iOS Team Inhouse Provisioning Profile: com.sinotruk.cnhtc.srm"
      
      ios_signing:
        distribution_type: enterprise
        bundle_identifier: com.sinotruk.cnhtc.srm

    scripts:
      - name: Set up code signing
        script: |
          # Install profiles and set up keychain
          xcode-project use-profiles
        
      - name: Build and Package Signed IPA
        script: |
          # 1. Create ExportOptions.plist using verified details
          cat > ExportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>enterprise</string>
              <key>teamID</key>
              <string>$TEAM_ID</string>
              <key>compileBitcode</key>
              <false/>
              <key>signingStyle</key>
              <string>manual</string>
              <key>provisioningProfiles</key>
              <dict>
                  <key>$BUNDLE_ID</key>
                  <string>$PROFILE_NAME</string>
              </dict>
          </dict>
          </plist>
          EOF

          # 2. Build Archive using verified details
          xcodebuild archive \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -archivePath build/LemonClicker.xcarchive \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            CODE_SIGN_IDENTITY="iPhone Distribution" \
            PROVISIONING_PROFILE_SPECIFIER="$PROFILE_NAME"

          # 3. Export IPA
          xcodebuild -exportArchive \
            -archivePath build/LemonClicker.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build/ipa
            
    artifacts:
      - build/ipa/*.ipa
      - /tmp/xcodebuild_log/*.log
      
    publishing:
      email:
        recipients:
          - user@example.com
