workflows:
  ios-signed-build:
    name: iOS Signed IPA Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    
    environment:
      vars:
        XCODE_PROJECT: "LemonClicker.xcodeproj"
        XCODE_SCHEME: "LemonClicker"
      
      ios_signing:
        distribution_type: enterprise
        bundle_identifier: com.viatris.myforceUAT

    scripts:
      - name: Set up code signing
        script: |
          # Automatically fetch the best matching certificate and profile
          xcode-project use-profiles
        
      - name: Build and Package Signed IPA
        script: |
          # Build and package into .ipa
          # The export-method will be inferred from the provisioning profile
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME" \
            --configuration Release \
            --output "build/ios/LemonClicker.ipa"
            
    artifacts:
      - build/ios/*.ipa
      - /tmp/xcodebuild_log/*.log
      
    publishing:
      email:
        recipients:
          - user@example.com
